# Generated by Django 5.2.7 on 2025-11-26 04:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complejos', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptoCobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('ORDINARIO', 'Ordinario'), ('EXTRAORDINARIO', 'Extraordinario')], max_length=20)),
                ('porcentaje_variacion', models.DecimalField(blank=True, decimal_places=2, help_text='Ej: 10 para 10%, -5 para -5%', max_digits=5, null=True)),
                ('obligatorio', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('TARJETA', 'Tarjeta'), ('CHEQUE', 'Cheque')], max_length=20)),
                ('cuenta_banco', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('comision', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='PlanCuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('frecuencia', models.CharField(choices=[('M', 'Mensual'), ('T', 'Trimestral'), ('S', 'Semestral')], default='M', max_length=1)),
                ('monto_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=20, unique=True)),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField()),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada'), ('VENCIDA', 'Vencida'), ('CANCELADA', 'Cancelada'), ('ANULADA', 'Anulada')], default='PENDIENTE', max_length=15)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='complejos.propiedad')),
                ('plan_cuota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.plancuota')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.CharField(max_length=255)),
                ('concepto_cobro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finanzas.conceptocobro')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='finanzas.factura')),
            ],
        ),
        migrations.CreateModel(
            name='Recaudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField()),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recaudos', to='finanzas.factura')),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finanzas.metodopago')),
                ('usuario_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
