# Generated by Django 5.2.7 on 2025-11-26 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complejos', '0002_initial'),
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptocobro',
            name='complejo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conceptos_cobro', to='complejos.complejo'),
        ),
        migrations.AddField(
            model_name='plancuota',
            name='complejo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes_cuota', to='complejos.complejo'),
        ),
    ]
