# Generated by Django 5.2.7 on 2025-11-26 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_conceptocobro_complejo_plancuota_complejo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conceptocobro',
            name='porcentaje_variacion',
        ),
        migrations.RemoveField(
            model_name='plancuota',
            name='monto_base',
        ),
        migrations.CreateModel(
            name='PlanConceptoCobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto específico para este concepto en este plan', max_digits=10)),
                ('orden', models.PositiveIntegerField(default=1, help_text='Orden en que aparece en la factura')),
                ('activo', models.BooleanField(default=True)),
                ('concepto_cobro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanzas.conceptocobro')),
                ('plan_cuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanzas.plancuota')),
            ],
            options={
                'ordering': ['orden'],
                'unique_together': {('plan_cuota', 'concepto_cobro')},
            },
        ),
        migrations.AddField(
            model_name='plancuota',
            name='conceptos',
            field=models.ManyToManyField(related_name='planes_cuota', through='finanzas.PlanConceptoCobro', to='finanzas.conceptocobro'),
        ),
    ]
