# Generated by Django 5.2.7 on 2025-11-28 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0003_remove_conceptocobro_porcentaje_variacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallefactura',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='monto_total',
        ),
    ]
