# Generated by Django 5.2.7 on 2025-11-29 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complejos', '0002_initial'),
        ('finanzas', '0004_remove_detallefactura_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plancuota',
            name='conceptos',
        ),
        migrations.CreateModel(
            name='ConfiguracionFinanciera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_corte', models.PositiveIntegerField(default=1, help_text='Día del mes en que se generan las facturas automáticamente (1-28)')),
                ('dias_vencimiento', models.PositiveIntegerField(default=15, help_text='Días de gracia después del corte antes de declarar mora')),
                ('tasa_interes_mora_diaria', models.DecimalField(decimal_places=3, default=0.033, help_text='Interés diario % (ej. 0.033% diario ≈ 1% mensual)', max_digits=5)),
                ('bloquear_servicios_con_deuda', models.BooleanField(default=False, help_text='Si es True, impide reservar amenidades si hay facturas vencidas')),
                ('complejo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_financiera', to='complejos.complejo')),
                ('plan_mantenimiento_default', models.ForeignKey(blank=True, help_text='Plan de cuotas (Gasto Común) que se aplica a TODOS los residentes activos', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_mantenimiento', to='finanzas.plancuota')),
            ],
        ),
        migrations.CreateModel(
            name='ContratoFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ALQUILER', 'Alquiler / Renta Mensual'), ('FINANCIAMIENTO', 'Financiamiento / Compra a Plazos')], max_length=20)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('PAUSADO', 'Pausado'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='ACTIVO', max_length=20)),
                ('monto_cuota', models.DecimalField(decimal_places=2, help_text='Monto a cobrar en cada periodo', max_digits=12)),
                ('fecha_inicio_pago', models.DateField(help_text='Fecha desde la cual se empieza a facturar')),
                ('dia_vencimiento_mensual', models.PositiveIntegerField(default=5, help_text='Día límite de pago para este concepto específico')),
                ('numero_cuotas_totales', models.PositiveIntegerField(blank=True, help_text='Solo para financiamiento: Total de cuotas pactadas (ej. 12, 24)', null=True)),
                ('cuotas_facturadas', models.PositiveIntegerField(default=0, help_text='Contador de cuotas ya generadas')),
                ('saldo_pendiente', models.DecimalField(blank=True, decimal_places=2, help_text='Deuda total restante del inmueble', max_digits=12, null=True)),
                ('propiedad_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos_financieros', to='complejos.propiedadpersona')),
            ],
        ),
    ]
