# Generated by Django 5.2.7 on 2025-12-06 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complejos', '0003_reserva_complejo'),
        ('finanzas', '0005_remove_plancuota_conceptos_configuracionfinanciera_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratofinanciero',
            name='monto_cuota',
        ),
        migrations.AddField(
            model_name='configuracionfinanciera',
            name='propiedad',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_financiera_especifica', to='complejos.propiedad'),
        ),
        migrations.AddField(
            model_name='contratofinanciero',
            name='plan_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_financieros', to='finanzas.plancuota'),
        ),
        migrations.AlterField(
            model_name='configuracionfinanciera',
            name='complejo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones_financieras', to='complejos.complejo'),
        ),
        migrations.AlterField(
            model_name='contratofinanciero',
            name='propiedad_persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contrato_financiero', to='complejos.propiedadpersona'),
        ),
        migrations.CreateModel(
            name='CargoAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('procesado', models.BooleanField(default=False, help_text='True si ya fue incluido en una factura')),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finanzas.conceptocobro')),
                ('factura_asociada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargos_origen', to='finanzas.factura')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos_adicionales', to='complejos.propiedad')),
            ],
        ),
    ]
