# Generated by Django 5.2.7 on 2025-12-08 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0006_remove_contratofinanciero_monto_cuota_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratofinanciero',
            name='dia_vencimiento_mensual',
        ),
        migrations.RemoveField(
            model_name='contratofinanciero',
            name='plan_pago',
        ),
        migrations.RemoveField(
            model_name='contratofinanciero',
            name='saldo_pendiente',
        ),
        migrations.RemoveField(
            model_name='contratofinanciero',
            name='tipo',
        ),
        migrations.AddField(
            model_name='contratofinanciero',
            name='adelanto',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Monto pagado al inicio (Entrada/Pie)', max_digits=12),
        ),
        migrations.AddField(
            model_name='contratofinanciero',
            name='configuracion_personalizada',
            field=models.BooleanField(default=False, help_text='Si es True, usa los conceptos definidos en ConceptoContrato. Si es False, usa la configuración del complejo.'),
        ),
        migrations.AddField(
            model_name='contratofinanciero',
            name='es_pago_contado',
            field=models.BooleanField(default=False, help_text='Si es compra al contado (sin cuotas)'),
        ),
        migrations.AddField(
            model_name='contratofinanciero',
            name='monto_pendiente',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Deuda total restante del inmueble tras el adelanto', max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='ConceptoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finanzas.conceptocobro')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conceptos', to='finanzas.contratofinanciero')),
            ],
        ),
    ]
