# Generated by Django 5.2.7 on 2025-12-08 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0007_remove_contratofinanciero_dia_vencimiento_mensual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratofinanciero',
            name='dia_corte',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Día del mes que se genera el cobro (1-28). Si es null, usa el del Complejo.', null=True),
        ),
        migrations.AddField(
            model_name='contratofinanciero',
            name='dias_vencimiento',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Días para pagar después del corte. Si es null, usa el del Complejo.', null=True),
        ),
        migrations.AddField(
            model_name='contratofinanciero',
            name='tasa_mora',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de mora diario/mensual. Si es null, usa el del Complejo.', max_digits=5, null=True),
        ),
    ]
