# Generated by Django 5.2.7 on 2025-12-08 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0008_contratofinanciero_dia_corte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratofinanciero',
            name='bloquear_servicios_con_deuda',
            field=models.BooleanField(default=False, help_text='Si se activa, el residente no podrá reservar amenidades si tiene deuda.'),
        ),
    ]
