# Generated by Django 5.2.7 on 2025-12-09 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0009_contratofinanciero_bloquear_servicios_con_deuda'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratofinanciero',
            name='plan',
            field=models.ForeignKey(blank=True, help_text='Plan de cuotas específico para este contrato', null=True, on_delete=django.db.models.deletion.PROTECT, to='finanzas.plancuota'),
        ),
        migrations.AddField(
            model_name='plancuota',
            name='es_plantilla',
            field=models.BooleanField(default=True, help_text='Si es True, es un modelo reutilizable. Si es False, es un plan personalizado de un contrato.'),
        ),
        migrations.AlterField(
            model_name='contratofinanciero',
            name='configuracion_personalizada',
            field=models.BooleanField(default=False, help_text='Si es True, usa un Plan Cuota específico. Si es False, usa la configuración del complejo.'),
        ),
        migrations.DeleteModel(
            name='ConceptoContrato',
        ),
    ]
