# Generated by Django 5.2.7 on 2025-12-09 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0010_contratofinanciero_plan_plancuota_es_plantilla_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plancuota',
            name='es_plantilla',
        ),
        migrations.AlterField(
            model_name='contratofinanciero',
            name='configuracion_personalizada',
            field=models.BooleanField(default=False, help_text='Si es True, usa una configuración financiera específica (fechas, tasas). Si es False, usa la configuración del complejo.'),
        ),
        migrations.AlterField(
            model_name='contratofinanciero',
            name='plan',
            field=models.ForeignKey(blank=True, help_text='Plan de cuotas (Conceptos de cobro) específico para este contrato', null=True, on_delete=django.db.models.deletion.PROTECT, to='finanzas.plancuota'),
        ),
    ]
