# Generated by Django 5.2.7 on 2025-12-09 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0011_remove_plancuota_es_plantilla_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratofinanciero',
            name='bloquear_servicios_con_deuda',
        ),
        migrations.RemoveField(
            model_name='contratofinanciero',
            name='dia_corte',
        ),
        migrations.RemoveField(
            model_name='contratofinanciero',
            name='dias_vencimiento',
        ),
        migrations.RemoveField(
            model_name='contratofinanciero',
            name='tasa_mora',
        ),
        migrations.AddField(
            model_name='configuracionfinanciera',
            name='es_personalizada',
            field=models.BooleanField(default=False, help_text='Si es True, es específica de un contrato y no se muestra en listas generales'),
        ),
        migrations.AddField(
            model_name='configuracionfinanciera',
            name='nombre',
            field=models.CharField(default='Configuración Estándar', help_text='Nombre para identificar esta configuración', max_length=100),
        ),
        migrations.AddField(
            model_name='contratofinanciero',
            name='configuracion',
            field=models.ForeignKey(blank=True, help_text='Configuración financiera específica (fechas, tasas). Si es null y configuracion_personalizada=False, usa la del complejo.', null=True, on_delete=django.db.models.deletion.PROTECT, to='finanzas.configuracionfinanciera'),
        ),
    ]
