# Generated by Django 5.2.7 on 2025-12-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0012_remove_contratofinanciero_bloquear_servicios_con_deuda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratofinanciero',
            name='tipo',
            field=models.CharField(choices=[('ALQUILER', 'Alquiler / Renta Mensual'), ('FINANCIAMIENTO', 'Financiamiento / Compra a Plazos')], default='ALQUILER', max_length=20),
        ),
    ]
