# Generated by Django 5.2.7 on 2025-12-09 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0013_contratofinanciero_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracionfinanciera',
            name='plan_mantenimiento_default',
        ),
    ]
