# Generated by Django 5.2.7 on 2025-12-09 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0014_remove_configuracionfinanciera_plan_mantenimiento_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionfinanciera',
            name='plan_mantenimiento_default',
            field=models.ForeignKey(blank=True, help_text='Plan de cuotas (Gasto Común) que se aplica si el residente no tiene plan personalizado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_mantenimiento', to='finanzas.plancuota'),
        ),
    ]
