# Generated by Django 5.2.7 on 2025-12-09 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0015_configuracionfinanciera_plan_mantenimiento_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='contrato',
            field=models.ForeignKey(blank=True, help_text='Contrato financiero que generó esta factura (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to='finanzas.contratofinanciero'),
        ),
    ]
