# Generated by Django 5.2.7 on 2025-12-09 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0016_factura_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratofinanciero',
            name='monto_cuota',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto fijo de la cuota mensual para financiamiento', max_digits=10, null=True),
        ),
    ]
