# Generated by Django 5.2.7 on 2025-12-10 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0017_contratofinanciero_monto_cuota'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefactura',
            name='descripcion',
            field=models.CharField(blank=True, help_text='Descripción opcional del detalle (ej. Cuota 1/12)', max_length=255, null=True),
        ),
    ]
