# Generated by Django 5.2.7 on 2025-12-12 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0018_detallefactura_descripcion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CargoAdicional',
        ),
    ]
