# Generated by Django 5.2.7 on 2025-12-19 01:59

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0019_delete_cargoadicional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metodopago',
            options={'ordering': ['tipo', 'nombre'], 'verbose_name': 'Método de Pago', 'verbose_name_plural': 'Métodos de Pago'},
        ),
        migrations.AlterModelOptions(
            name='recaudo',
            options={'ordering': ['-fecha_pago', '-created_at'], 'verbose_name': 'Recaudo', 'verbose_name_plural': 'Recaudos'},
        ),
        migrations.RenameField(
            model_name='metodopago',
            old_name='cuenta_banco',
            new_name='numero_cuenta',
        ),
        migrations.RemoveField(
            model_name='metodopago',
            name='comision',
        ),
        migrations.RemoveField(
            model_name='recaudo',
            name='referencia',
        ),
        migrations.AddField(
            model_name='metodopago',
            name='banco',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='metodopago',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metodopago',
            name='requiere_aprobacion',
            field=models.BooleanField(default=False, help_text="Si es True, el pago queda en estado 'pendiente de aprobación'"),
        ),
        migrations.AddField(
            model_name='metodopago',
            name='tipo_cuenta',
            field=models.CharField(blank=True, choices=[('CORRIENTE', 'Corriente'), ('AHORROS', 'Ahorros'), ('CCI', 'CCI')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='metodopago',
            name='titular_cuenta',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='metodopago',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='recaudo',
            name='banco_origen',
            field=models.CharField(blank=True, help_text='Banco desde donde se realizó la transferencia', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recaudo',
            name='billetera_numero_celular',
            field=models.CharField(blank=True, help_text='Número de celular asociado a la billetera', max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\+?[\\d\\s\\-]{7,20}$', 'Formato de teléfono inválido')]),
        ),
        migrations.AddField(
            model_name='recaudo',
            name='billetera_numero_transaccion',
            field=models.CharField(blank=True, help_text='ID de transacción de la billetera digital', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recaudo',
            name='comprobante_imagen',
            field=models.ImageField(blank=True, help_text='Captura de pantalla del comprobante', null=True, upload_to='comprobantes/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='recaudo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recaudo',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Aprobación'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='APROBADO', max_length=15),
        ),
        migrations.AddField(
            model_name='recaudo',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recaudo',
            name='motivo_rechazo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recaudo',
            name='numero_operacion',
            field=models.CharField(blank=True, help_text='Número de operación o referencia bancaria', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recaudo',
            name='numero_tarjeta',
            field=models.CharField(blank=True, help_text='Número de tarjeta (se enmascarará al guardar)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='recaudo',
            name='recibido_por',
            field=models.CharField(blank=True, help_text='Nombre de quien recibió el efectivo (Gerente, Administrador, etc.)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='recaudo',
            name='tarjeta_numero_autorizacion',
            field=models.CharField(blank=True, help_text='Código de autorización del banco', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='recaudo',
            name='tarjeta_tipo',
            field=models.CharField(blank=True, choices=[('VISA', 'Visa'), ('MASTERCARD', 'Mastercard'), ('AMEX', 'American Express'), ('OTRO', 'Otro')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='recaudo',
            name='tarjeta_titular',
            field=models.CharField(blank=True, help_text='Nombre del titular como aparece en la tarjeta', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='recaudo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='recaudo',
            name='usuario_aprobacion',
            field=models.ForeignKey(blank=True, help_text='Usuario que aprobó el pago', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recaudos_aprobados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='metodopago',
            name='nombre',
            field=models.CharField(help_text="Nombre del método (ej: 'Visa Crédito', 'Yape', 'Efectivo Administración')", max_length=100),
        ),
        migrations.AlterField(
            model_name='metodopago',
            name='tipo',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('TARJETA', 'Tarjeta de Crédito/Debito'), ('BILLETERA_DIGITAL', 'Billetera Digital (Yape, Plin, etc.)'), ('DEPOSITO_BANCARIO', 'Depósito Bancario')], max_length=30),
        ),
        migrations.AlterField(
            model_name='recaudo',
            name='fecha_pago',
            field=models.DateField(help_text='Fecha en que se realizó el pago'),
        ),
        migrations.AlterField(
            model_name='recaudo',
            name='monto_pagado',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='recaudo',
            name='usuario_registro',
            field=models.ForeignKey(help_text='Usuario que registró el pago', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recaudos_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='recaudo',
            index=models.Index(fields=['fecha_pago', 'estado'], name='finanzas_re_fecha_p_f3f532_idx'),
        ),
        migrations.AddIndex(
            model_name='recaudo',
            index=models.Index(fields=['factura', 'estado'], name='finanzas_re_factura_566376_idx'),
        ),
    ]
