# Generated by Django 5.2.7 on 2025-12-19 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0020_alter_metodopago_options_alter_recaudo_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metodopago',
            name='titular_cuenta',
        ),
    ]
