# Generated by Django 5.2.7 on 2025-12-19 21:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0021_remove_metodopago_titular_cuenta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recaudo',
            name='tarjeta_numero_autorizacion',
        ),
        migrations.AddField(
            model_name='recaudo',
            name='codigo_cvv',
            field=models.CharField(blank=True, help_text='Código de seguridad', max_length=3, null=True, validators=[django.core.validators.RegexValidator('^\\d{3}$', 'El CVV debe tener 3 dígitos')]),
        ),
        migrations.AddField(
            model_name='recaudo',
            name='fecha_expiracion',
            field=models.CharField(blank=True, help_text='Formato MM/YY', max_length=5, null=True, validators=[django.core.validators.RegexValidator('^\\d{2}/\\d{2}$', 'Formato inválido. Use MM/YY')]),
        ),
    ]
