# Generated by Django 5.2.7 on 2025-12-19 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0022_remove_recaudo_tarjeta_numero_autorizacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conceptocobro',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='recaudo',
            name='observaciones',
        ),
    ]
