# Generated by Django 5.2.7 on 2025-11-26 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('GERENTE', 'Gerente'), ('RESIDENTE', 'Residente'), ('GUARDIA', 'Guardia')], default='RESIDENTE', max_length=15),
        ),
    ]
