# Generated by Django 5.2.7 on 2025-10-15 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidades', '0001_initial'),
        ('users', '0002_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='comunidad_asignada',
            field=models.ForeignKey(blank=True, help_text='Comunidad a la que está asignado el portero.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='comunidades.comunidad'),
        ),
    ]
