# Generated by Django 5.2.7 on 2025-10-24 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complejos', '0001_initial'),
        ('users', '0002_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='complejo_asignado',
            field=models.ForeignKey(blank=True, help_text='Complejo al que está asignado el portero.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='complejos.complejo'),
        ),
    ]
