# Generated by Django 5.2.7 on 2025-11-05 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complejos', '0005_alter_propiedadpersona_porcentaje_propiedad_and_more'),
        ('users', '0004_persona_customuser_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='complejo_asignado',
            field=models.ForeignKey(blank=True, help_text='Complejo al que está asignado el guardia.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='complejos.complejo'),
        ),
    ]
