# Generated by Django 5.2.7 on 2025-10-13 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Condominio El Sol', max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_identificador', models.CharField(help_text='Ej: Departamento 101, Casa 25B', max_length=20)),
                ('tipo_contrato', models.CharField(choices=[('PROPIETARIO', 'Propietario'), ('INQUILINO', 'Inquilino'), ('TEMPORAL', 'Temporal')], default='PROPIETARIO', max_length=20)),
                ('comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propiedades', to='comunidades.comunidad')),
                ('residente_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propiedades_habitadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
