# Generated by Django 5.2.7 on 2025-11-08 01:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complejos', '0008_alter_complejo_telefono_contacto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('tipo_aviso', models.CharField(choices=[('GENERAL', 'General'), ('MANTENIMIENTO', 'Mantenimiento'), ('URGENTE', 'Urgente'), ('SUGERENCIA', 'Sugerencia')], default='GENERAL', max_length=20)),
                ('dirigido_a', models.CharField(choices=[('TODOS', 'Todos'), ('RESIDENTES', 'Residentes'), ('ADMINISTRADORES', 'Administradores')], default='TODOS', max_length=20)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos_creados', to=settings.AUTH_USER_MODEL)),
                ('complejo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos', to='complejos.complejo')),
                ('leido_por', models.ManyToManyField(blank=True, related_name='avisos_leidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
