# Generated by Django 5.2.7 on 2025-11-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('tipo_aviso', models.CharField(choices=[('GENERAL', 'General'), ('MANTENIMIENTO', 'Mantenimiento'), ('URGENTE', 'Urgente')], default='GENERAL', max_length=20)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
