# Generated by Django 5.2.7 on 2025-11-08 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('avisos', '0001_initial'),
        ('complejos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aviso',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos_creados_nuevos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aviso',
            name='complejo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos_nuevos', to='complejos.complejo'),
        ),
        migrations.AddField(
            model_name='aviso',
            name='leido_por',
            field=models.ManyToManyField(blank=True, related_name='avisos_leidos_nuevos', to=settings.AUTH_USER_MODEL),
        ),
    ]
