# Generated by Django 5.2.7 on 2025-11-08 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complejos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('DNI', 'DNI'), ('Pasaporte', 'Pasaporte'), ('Carnet Extranjeria', 'Carnet de Extranjería')], max_length=20)),
                ('numero_documento', models.CharField(max_length=20, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('foto_capturada', models.ImageField(blank=True, null=True, upload_to='visitantes/')),
                ('es_frecuente', models.BooleanField(default=False)),
                ('fecha_registro_sistema', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('bloqueado', 'Bloqueado')], default='activo', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PreAutorizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_visitante', models.CharField(max_length=200)),
                ('documento_visitante', models.CharField(max_length=20)),
                ('fecha_hora_esperada', models.DateTimeField()),
                ('vigencia_desde', models.DateTimeField()),
                ('vigencia_hasta', models.DateTimeField()),
                ('es_recurrente', models.BooleanField(default=False)),
                ('dias_semana', models.CharField(blank=True, help_text='Ej: lunes,martes,viernes', max_length=50)),
                ('usado', models.BooleanField(default=False)),
                ('fecha_uso', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('usado', 'Usado'), ('vencido', 'Vencido'), ('cancelado', 'Cancelado')], default='pendiente', max_length=10)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complejos.propiedad')),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_ingreso', models.DateTimeField()),
                ('fecha_hora_salida', models.DateTimeField(blank=True, null=True)),
                ('motivo_visita', models.CharField(choices=[('social', 'Social'), ('proveedor', 'Proveedor'), ('delivery', 'Delivery'), ('mudanza', 'Mudanza'), ('tecnico', 'Técnico')], max_length=20)),
                ('placa_vehiculo', models.CharField(blank=True, max_length=10)),
                ('cantidad_acompanantes', models.PositiveIntegerField(default=0)),
                ('autorizado_previamente', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('en_curso', 'En curso'), ('finalizado', 'Finalizado'), ('no_autorizado', 'No Autorizado')], default='en_curso', max_length=15)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complejos.propiedad')),
                ('residente_autoriza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas_autorizadas', to=settings.AUTH_USER_MODEL)),
                ('usuario_registra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas_registradas', to=settings.AUTH_USER_MODEL)),
                ('visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitas.visitante')),
            ],
        ),
    ]
