# Generated by Django 5.2.7 on 2025-11-08 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='estado',
            field=models.CharField(choices=[('en_curso', 'En curso'), ('finalizado', 'Finalizado'), ('no_autorizado', 'No Autorizado')], default='en_curso', max_length=15),
        ),
    ]
