# Generated by Django 5.2.7 on 2025-11-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitante',
            name='numero_documento',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='telefono',
            field=models.CharField(blank=True, max_length=9),
        ),
    ]
