# Generated by Django 5.2.7 on 2025-10-24 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complejo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('calle', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('tipo', models.CharField(choices=[('residencial', 'Residencial'), ('condominio', 'Condominio')], max_length=20)),
                ('numero_total_unidades', models.PositiveIntegerField()),
                ('amenidades', models.TextField()),
                ('administrador_responsable', models.CharField(max_length=100)),
                ('telefono_contacto', models.CharField(max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_identificador', models.CharField(help_text='Ej: "101", "A-5", "Torre 2 - 304"', max_length=20)),
                ('tipo', models.CharField(choices=[('departamento', 'Departamento'), ('casa', 'Casa')], max_length=20)),
                ('area', models.DecimalField(decimal_places=2, max_digits=8)),
                ('numero_habitaciones', models.PositiveIntegerField()),
                ('numero_banos', models.PositiveIntegerField()),
                ('piso_nivel', models.CharField(max_length=10)),
                ('valor_estimado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('estado_ocupacion', models.CharField(choices=[('disponible', 'Disponible'), ('ocupado', 'Ocupado'), ('mantenimiento', 'En mantenimiento')], default='disponible', max_length=20)),
                ('complejo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propiedades', to='complejos.complejo')),
                ('residente_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propiedades_habitadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
