# Generated by Django 5.2.7 on 2025-11-08 17:08

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('capacidad', models.PositiveIntegerField(default=1, help_text='Capacidad máxima de personas')),
                ('reglas', models.TextField(blank=True, help_text='Reglas de uso de la amenidad', null=True)),
                ('hora_inicio', models.TimeField(default=datetime.time(8, 0))),
                ('hora_fin', models.TimeField(default=datetime.time(22, 0))),
            ],
        ),
        migrations.CreateModel(
            name='PropiedadPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_relacion', models.CharField(choices=[('propietario', 'Propietario'), ('inquilino', 'Inquilino'), ('co-propietario', 'Co-propietario'), ('co-inquilino', 'Co-inquilino')], max_length=20)),
                ('porcentaje_propiedad', models.DecimalField(blank=True, choices=[(100.0, '100%'), (50.0, '50%')], decimal_places=2, help_text='Para co-propietarios', max_digits=5, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, help_text='Solo para inquilinos', null=True)),
                ('es_principal', models.BooleanField(default=False, help_text='Para identificar el responsable principal')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('completada', 'Completada'), ('bloqueada', 'Bloqueada')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Complejo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('calle', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('tipo', models.CharField(choices=[('residencial', 'Residencial'), ('condominio', 'Condominio')], max_length=20)),
                ('numero_total_unidades', models.PositiveIntegerField()),
                ('administrador_responsable', models.CharField(max_length=100)),
                ('telefono_contacto', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe tener exactamente 9 dígitos.', regex='^\\d{9}$')])),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
                ('amenidades', models.ManyToManyField(to='complejos.amenidad')),
            ],
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_identificador', models.CharField(help_text='Ej: "101", "A-5", "Torre 2 - 304"', max_length=20)),
                ('tipo', models.CharField(choices=[('departamento', 'Departamento'), ('casa', 'Casa')], max_length=20)),
                ('area', models.DecimalField(decimal_places=2, max_digits=8)),
                ('numero_habitaciones', models.PositiveIntegerField()),
                ('numero_banos', models.PositiveIntegerField()),
                ('piso_nivel', models.CharField(max_length=10)),
                ('valor_estimado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('estado_ocupacion', models.CharField(choices=[('disponible', 'Disponible'), ('ocupado', 'Ocupado'), ('mantenimiento', 'En mantenimiento')], default='disponible', max_length=20)),
                ('complejo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propiedades', to='complejos.complejo')),
            ],
        ),
    ]
