# Generated by Django 5.2.7 on 2025-10-25 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complejos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='complejo',
            name='amenidades',
        ),
        migrations.AddField(
            model_name='complejo',
            name='amenidades',
            field=models.ManyToManyField(to='complejos.amenidad'),
        ),
    ]
