# Generated by Django 5.2.7 on 2025-11-08 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complejos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedadpersona',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propiedades_asociadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propiedadpersona',
            name='propiedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personas_asociadas', to='complejos.propiedad'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='residentes',
            field=models.ManyToManyField(related_name='propiedades_habitadas', through='complejos.PropiedadPersona', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reserva',
            name='amenidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='complejos.amenidad'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='residente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL),
        ),
    ]
