# Generated by Django 5.2.7 on 2025-10-25 01:00

from django.db import migrations

def populate_amenidades(apps, schema_editor):
    Amenidad = apps.get_model('complejos', 'Amenidad')
    amenidades = [
        'cancha deportiva',
        'piscina',
        'gimnasio',
        'salon de eventos'
    ]
    for nombre in amenidades:
        Amenidad.objects.create(nombre=nombre)

class Migration(migrations.Migration):

    dependencies = [
        ('complejos', '0002_amenidad_remove_complejo_amenidades_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_amenidades),
    ]
