# Generated by Django 5.2.7 on 2025-11-29 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complejos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='complejo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='complejos.complejo'),
        ),
    ]
