# Generated by Django 5.2.7 on 2025-11-04 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complejos', '0003_populate_amenidades'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propiedad',
            name='residente_actual',
        ),
        migrations.CreateModel(
            name='PropiedadPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_relacion', models.CharField(choices=[('propietario', 'Propietario'), ('inquilino', 'Inquilino'), ('co-propietario', 'Co-propietario'), ('avalista', 'Avalista')], max_length=20)),
                ('porcentaje_propiedad', models.DecimalField(blank=True, decimal_places=2, help_text='Para co-propietarios', max_digits=5, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, help_text='Solo para inquilinos', null=True)),
                ('es_principal', models.BooleanField(default=False, help_text='Para identificar el responsable principal')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propiedades_asociadas', to=settings.AUTH_USER_MODEL)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personas_asociadas', to='complejos.propiedad')),
            ],
        ),
        migrations.AddField(
            model_name='propiedad',
            name='residentes',
            field=models.ManyToManyField(related_name='propiedades_habitadas', through='complejos.PropiedadPersona', to=settings.AUTH_USER_MODEL),
        ),
    ]
