# Generated by Django 5.2.7 on 2025-12-14 17:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complejos', '0003_reserva_complejo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complejo',
            name='administrador_responsable',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='complejo',
            name='telefono_contacto',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe tener exactamente 9 dígitos.', regex='^\\d{9}$')]),
        ),
    ]
