# Generated by Django 5.2.7 on 2025-12-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complejos', '0004_alter_complejo_administrador_responsable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenidad',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
