# Generated by Django 5.2.7 on 2025-11-05 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complejos', '0004_remove_propiedad_residente_actual_propiedadpersona_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedadpersona',
            name='porcentaje_propiedad',
            field=models.DecimalField(blank=True, choices=[(100.0, '100%'), (50.0, '50%')], decimal_places=2, help_text='Para co-propietarios', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='propiedadpersona',
            name='tipo_relacion',
            field=models.CharField(choices=[('propietario', 'Propietario'), ('inquilino', 'Inquilino'), ('co-propietario', 'Co-propietario'), ('co-inquilino', 'Co-inquilino')], max_length=20),
        ),
    ]
