# Generated by Django 5.2.7 on 2025-11-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complejos', '0005_alter_reserva_estado_alter_reserva_residente'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenidad',
            name='capacidad',
            field=models.PositiveIntegerField(default=1, help_text='Capacidad máxima de personas'),
        ),
        migrations.AddField(
            model_name='amenidad',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='amenidad',
            name='horario_disponibilidad',
            field=models.CharField(blank=True, help_text='Ej: Lunes a Viernes de 9:00 a 22:00', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='amenidad',
            name='reglas',
            field=models.TextField(blank=True, help_text='Reglas de uso de la amenidad', null=True),
        ),
    ]
