# Generated by Django 5.2.7 on 2025-11-07 19:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complejos', '0006_amenidad_capacidad_amenidad_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenidad',
            name='horario_disponibilidad',
        ),
        migrations.AddField(
            model_name='amenidad',
            name='hora_fin',
            field=models.TimeField(default=datetime.time(22, 0)),
        ),
        migrations.AddField(
            model_name='amenidad',
            name='hora_inicio',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
    ]
