# Generated by Django 5.2.7 on 2025-11-08 01:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complejos', '0007_remove_amenidad_horario_disponibilidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complejo',
            name='telefono_contacto',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe tener exactamente 9 dígitos.', regex='^\\d{9}$')]),
        ),
    ]
