# Generated by Django 5.2.7 on 2025-10-15 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comunidades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('DNI', 'DNI'), ('CARNET_EXTRANJERIA', 'Carnet de Extranjería'), ('PASAPORTE', 'Pasaporte')], max_length=20)),
                ('numero_documento', models.CharField(max_length=20)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_visita', models.DateField()),
                ('hora_entrada', models.TimeField()),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comunidades.comunidad')),
                ('residente_visitado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas_recibidas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
